service: products
frameworkVersion: "3"
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3

provider:
  name: aws
  runtime: nodejs20.x
  # layers:
  #   - ${ssm:NODE_LAYER}
  # deploymentBucket:
  #   name: ${ssm:DEPLOYMENT_BUCKET}
  #   maxPreviousDeploymentArtifacts: 10
  #   blockPublicAccess: true
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION}
  versionFunctions: false

  environment:
    REGION: ${env:REGION}
    DEBUG: ${env:DEBUG}
    STAGE: ${self:provider.stage}
    PRODUCTS_TABLE: ${self:service}-${self:provider.stage}
    PRODUCTS_BUCKET: ${self:service}-storage-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:Query
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.PRODUCTS_TABLE}"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource:
            - "arn:aws:s3:::${self:provider.environment.PRODUCTS_BUCKET}/*"

package:
  patterns:
    - dist/** # Include only compiled JS files
    - templates/** # Include html templates
    # - "!node_modules/**" # Exclude dependencies
    - "!lib/**" # Exclude raw TypeScript files in lib
    - "!entities/**" # Exclude raw TypeScript files in entities
    - "!.git/**" # Exclude Git metadata
    - "!docs/**" # Exclude documentation
    - "!**/*.ts" # Exclude all TypeScript files
    - "!tsconfig.json" # Exclude tsconfig.json

custom:
  # Scripts to build project when deploying and running SLS Offline
  scripts:
    hooks:
      # Run before the packaging process
      "package:initialize": |
        # Navigate to the root directory and run ts-build.sh
        echo "Building service before deployment - Running ts-build.sh"
        cd ../ || { echo "Failed to navigate to the project root"; exit 1; }
        echo "Current directory: $(pwd)"

        # Run the ts-build.sh script
        chmod +x ts-build.sh || { echo "Failed to make ts-build.sh executable"; exit 1; }
        ./ts-build.sh interface ${self:service} || { echo "Build for ${self:service} failed"; exit 1; }
        echo "Build completed for ${self:service}"

      # Run before invoking serverless offline
      "before:offline:start": |
        # Navigate to the root directory and run ts-build.sh
        echo "Building service before deployment - Running ts-build.sh"
        cd ../ || { echo "Failed to navigate to the project root"; exit 1; }
        echo "Current directory: $(pwd)"

        # Run the ts-build.sh script
        chmod +x ts-build.sh || { echo "Failed to make ts-build.sh executable"; exit 1; }
        ./ts-build.sh interface ${self:service} || { echo "Build for ${self:service} failed"; exit 1; }
        echo "Build completed for ${self:service}"

  # customDomain:
  #   rest:
  #     domainName: "localhost" # ${ssm:DOMAIN_NAME}
  #     stage: ${opt:stage, self:provider.stage}
  #     basePath: ${self:service}
  #     certificateName: "offline-cert" # ${ssm:DOMAIN_CERTIFICATE}
  #     createRoute53Record: true
  #     securityPolicy: tls_1_2
  #     endpointType: REGIONAL

plugins:
  - serverless-offline
  # - serverless-domain-manager
  - serverless-plugin-scripts

functions:
  createProduct:
    handler: dist/handlers/createProduct.handler
    events:
      - http:
          path: products
          method: post
          cors: true

  getAllProducts:
    handler: dist/handlers/getAllProducts.handler
    events:
      - http:
          path: products
          method: get
          cors: true

  getProductById:
    handler: dist/handlers/getProductById.handler
    events:
      - http:
          path: products/{id}
          method: get
          cors: true

  updateProduct:
    handler: dist/handlers/updateProduct.handler
    events:
      - http:
          path: products/{id}
          method: put
          cors: true
      - http:
          path: products/{id}
          method: patch
          cors: true

  deleteProduct:
    handler: dist/handlers/deleteProduct.handler
    events:
      - http:
          path: products/{id}
          method: delete
          cors: true

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRODUCTS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
        GlobalSecondaryIndexes:
          - IndexName: ProductsByTypeIndex
            KeySchema:
              - AttributeName: type
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    ProductsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PRODUCTS_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ["*"]
              AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
              AllowedOrigins: ["*"]

    ProductsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ProductsBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action: s3:GetObject
              Resource: !Sub "arn:aws:s3:::${ProductsBucket}/*"
